// src/molecules/Header.jsx
import React, { useEffect } from "react";
// import { NavLink} from 'react-router-dom';
import { NavLink, Link } from 'react-router-dom';
import { HashLink } from 'react-router-hash-link';
import logo from "../icons/logo.png";
import "../styles/Header.scss";


const Header = (MenuList) => {
  console.log(MenuList)
  useEffect(() => {
    const mobile = window.matchMedia("(max-width: 700px)")

    let menu = document.getElementById('menu_categories');
    const menuPrepend = (mobile)=>{
      if(mobile.matches){
        document.querySelector('aside').append(menu);
      }else{
        document.querySelector('header .main_menu_wrapper').append(menu);
      }
    }
    menuPrepend(mobile);
    window.addEventListener('resize', ()=>{
      menuPrepend(mobile);
    })
    document.getElementById('menu_open').addEventListener('click', ()=>{
      let menu = document.querySelector('aside');
      if(menu.classList.contains('d-none')){
        menu.classList.remove('d-none')
        menu.classList.add('d-flex')
      }else{
        menu.classList.add('d-none')
        menu.classList.remove('d-flex')
      }
    })
    document.querySelector('.container_main').addEventListener('click', ()=>{
      let menu = document.querySelector('aside');
        menu.classList.add('d-none')
        menu.classList.remove('d-flex')
      
    })
  });
  return (
    <header className="d-flex flex-wrap align-content-start py-0">
      <div className="container d-flex flex-wrap main_menu">
        <div className="col-4 logo d-flex justify-content-center align-items-start"><NavLink to="/"><img src={logo} alt="bud-walczak_logo" /></NavLink></div>
        <div className="d-flex col-8 flex-wrap main_menu_wrapper"> 
          <i id="menu_open" className="icon-menu-mobile d-flex d-md-none align-items-center"></i>
          <ul id="menu_categories" className="d-flex w-100 flex-wrap flex-md-nowrap justify-content-end align-content-start align-items-center container">
            {
              Object.keys(MenuList.Menu).map(element => 
                <li><HashLink smooth="true" to={"#" + MenuList.Menu[element].link} className="btn text-center text-uppercase h-100 scrollTo"> {MenuList.Menu[element].name} </HashLink></li>
              )
            }
          </ul>
        </div>
      </div>
      <aside className="d-none flex-wrap"></aside>
    </header>
  );
};

export default Header;

// src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  equipment = [
    {
      "link": "about-us" ,
      "name": "O firmie"
    },
    {
      "link": "contact" ,
      "name": "Kontakt"
    }
  ];
  homes= [
    {
      "link": "gallery" ,
      "name": "Galeria"
    },
    {
      "link": "about-us" ,
      "name": "O firmie"
    },
    {
      "link": "contact" ,
      "name": "Kontakt"
    }
  ];
  // menu$ = this.homes;
  menu$: any;
  constructor(
    private location: Location,
  ) {}
  scrollTo(element: any): void {
    (document.getElementById(element) as HTMLElement).scrollIntoView({behavior: "smooth", block: "start", inline: "nearest"});
  }
  ngOnInit(): void {
    if(this.location.path().includes('/houses')){
      this.menu$ = this.homes;
    }else if(this.location.path().includes('/equipment')){
      this.menu$ = this.equipment;
    }

    const mobile = window.matchMedia("(max-width: 768px)")
    let menu = document.getElementById('menu_categories');
    const menuPrepend = (mobile)=>{
      if(mobile.matches){
        document.querySelector('aside').append(menu);
      }else{
        document.querySelector('header .main_menu_wrapper').append(menu);
      }
    }
    menuPrepend(mobile);
    window.addEventListener('resize', ()=>{
      menuPrepend(mobile);
    })
    document.getElementById('menu_open').addEventListener('click', ()=>{
      let menu = document.querySelector('aside');
      if(menu.classList.contains('d-none')){
        menu.classList.remove('d-none')
        menu.classList.add('d-flex')
      }else{
        menu.classList.add('d-none')
        menu.classList.remove('d-flex')
      }
    })
    document.querySelector('.container_main').addEventListener('click', ()=>{
      let menu = document.querySelector('aside');
        menu.classList.add('d-none')
        menu.classList.remove('d-flex')

    })
  }
}

<header class="d-flex flex-wrap align-content-start py-0">
  <div class="container d-flex flex-wrap main_menu">
    <div class="col-4 logo d-flex justify-content-center align-items-start">
      <a href="/"><img src="../../assets/icons/logo.png" alt="bud-walczak_logo" /></a>
    </div>
    <div class="d-flex col-8 flex-wrap main_menu_wrapper">
      <i id="menu_open" class="icon-menu-mobile d-flex d-md-none align-items-center"></i>
      <ul id="menu_categories" class="d-flex w-100 flex-wrap flex-md-nowrap justify-content-end align-content-start align-items-center container">
        <li *ngFor="let item of menu$">
          <a (click)="scrollTo(item.link)" class="btn text-center text-uppercase h-100 scrollTo">
            {{item.name}}
          </a>
        </li>
      </ul>
    </div>
  </div>
  <aside class="d-none flex-wrap"></aside>
</header>
